[tool.ruff]
lint.ignore = ["E501", "E712"]

[tool.poetry]
authors = ["Badr B. (swve)"]
description = "Learnhouse Backend"
name = "learnhouse-api"
package-mode = false
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
boto3 = "^1.34.17"
botocore = "^1.34.74"
chromadb = "^0.4.22"
faker = "^24.4.0"
fastapi = "^0.110.0"
fastapi-jwt-auth = "^0.5.0"
httpx = "^0.27.0"
langchain = "0.1.0"
langchain-community = "^0.0.11"
langchain-openai = "^0.0.6"
openai = "^1.7.1"
passlib = "^1.7.4"
psycopg2-binary = "^2.9.9"
pydantic = {version = ">=1.8.0,<2.0.0", extras = ["email"]}
pytest = "^8.1.1"
python = "^3.12"
python-dotenv = "^1.0.0"
python-jose = "^3.3.0"
python-multipart = "^0.0.9"
pyyaml = "^6.0.1"
redis = "^5.0.1"
requests = "^2.31.0"
resend = "^0.8.0"
sentry-sdk = {extras = ["fastapi"], version = "^1.39.2"}
sqlmodel = "^0.0.10"
tiktoken = "^0.5.2"
uvicorn = "0.29.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
