[tool.ruff]
lint.ignore = ["E501", "E712"]

[tool.poetry]
authors = ["Badr B. (swve)"]
description = "Learnhouse Backend"
name = "learnhouse-api"
package-mode = false
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
boto3 = "^1.34.79"
botocore = "^1.34.93"
faker = "^30.1.0"
fastapi = "^0.115.0"
fastapi-jwt-auth = "^0.5.0"
httpx = "^0.27.0"
langchain = "^0.1.7"
langchain-community = "^0.0.20"
langchain-openai = "^0.0.6"
openai = "^1.50.2"
passlib = "^1.7.4"
psycopg2-binary = "^2.9.9"
pydantic = {version = ">=1.8.0,<2.0.0", extras = ["email"]}
pytest = "^8.2.2"
python = "^3.12"
python-dotenv = "^1.0.0"
python-jose = "^3.3.0"
python-multipart = "^0.0.9"
pyyaml = "^6.0.1"
redis = "^5.0.7"
requests = "^2.32.3"
resend = "^2.4.0"
sentry-sdk = {extras = ["fastapi"], version = "^2.13.0"}
sqlmodel = "^0.0.19"
tiktoken = "^0.7.0"
uvicorn = "0.30.1"
typer = "^0.12.5"
chromadb = "^0.5.13"
alembic = "^1.13.2"
alembic-postgresql-enum = "^1.2.0"
sqlalchemy-utils = "^0.41.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
